import { SessionProgress } from '../types/coaching';

export const exportSessionSummary = (sessionData: Partial<SessionProgress>) => {
  const timestamp = new Date().toISOString().split('T')[0];
  const summary = {
    date: new Date().toLocaleDateString(),
    sessionDuration: `${Math.round(sessionData.timeSpent || 0)} minutes`,
    skillsPracticed: sessionData.skillsAttempted?.length || 0,
    confidenceLevel: `${sessionData.confidenceScore || 0}/10`,
    engagementLevel: `${sessionData.engagementLevel || 0}/10`,
    achievements: sessionData.achievementsUnlocked || [],
    skillsDetail: sessionData.skillsAttempted || []
  };

  const content = `
# TeenThrive Independence Session Summary

**Date:** ${summary.date}
**Session Duration:** ${summary.sessionDuration}

## 🎯 Session Overview
- **Skills Practiced:** ${summary.skillsPracticed}
- **Confidence Level:** ${summary.confidenceLevel}
- **Engagement Level:** ${summary.engagementLevel}

## 🏆 Achievements Unlocked
${summary.achievements.length > 0 
  ? summary.achievements.map(achievement => `- ${achievement}`).join('\n')
  : '- No achievements unlocked this session (keep going!)'
}

## 📚 Skills Practiced
${summary.skillsDetail.length > 0
  ? summary.skillsDetail.map((skill: any) => 
      `- **${skill.skill}** - ${skill.success ? '✅ Success' : '⏳ Practice'} (${skill.timestamp.toLocaleTimeString()})`
    ).join('\n')
  : '- No skills practiced this session'
}

## 🌟 Your Independence Journey
Great job taking steps toward independence! Every skill you practice and every challenge you complete brings you closer to becoming a confident, capable adult.

Remember: Independence isn't about doing everything alone - it's about having the confidence and skills to handle life's challenges when they come your way.

---
*Generated by TeenThrive - Your AI Independence Coach*
*This summary is private and not stored permanently*
  `.trim();

  // Create and download the file
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `TeenThrive-Session-${timestamp}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportSessionCertificate = (sessionData: Partial<SessionProgress>) => {
  const achievements = sessionData.achievementsUnlocked || [];
  const skillCount = sessionData.skillsAttempted?.length || 0;
  
  if (achievements.length === 0 && skillCount === 0) {
    alert('Complete some activities first to generate a certificate!');
    return;
  }

  const content = `
🏆 CERTIFICATE OF INDEPENDENCE PROGRESS 🏆

This certifies that the bearer has demonstrated
commitment to developing independence skills

Session Date: ${new Date().toLocaleDateString()}
Skills Practiced: ${skillCount}
Confidence Growth: ${sessionData.confidenceScore || 0}/10

Achievements Earned:
${achievements.map(achievement => `⭐ ${achievement}`).join('\n')}

"Every step toward independence is a step toward your best self."

TeenThrive AI Independence Coach
  `.trim();

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `TeenThrive-Certificate-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};